In [1]:
import numpy as np 

# 1 . Create a NumPy array containing numbers from 1–100.

In [9]:
r = np.arange(1,101)

r

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [10]:
type(r)

numpy.ndarray

# 2. Find the mean, median, standard deviation, minimum and maximum.

In [21]:
print(r.mean())
print(r.std())
print(r.min())
print(r.max())
print(np.median(r))

50.5
28.86607004772212
1
100
50.5


# 3 . Replace all negative values in an array with 0.

In [30]:
arr  = np.array([1,-1,2,-2,3,-3,4,-4])

arr[arr<1] = 0
arr

array([1, 0, 2, 0, 3, 0, 4, 0])

# 4. Find all values greater than the array's mean.

In [43]:
arr = np.arange(1,51)


m = arr.mean() 

arr[m < arr]

array([26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42,
       43, 44, 45, 46, 47, 48, 49, 50])