# 12 Find duplicate rows in a NumPy matrix.

In [27]:
import numpy as np
arr = np.array([[1, 2, 3],
    [4, 5, 6],
    [1, 2, 3],
    [7, 8, 9],
    [4, 5, 6],
    [10, 11, 12]])
print(arr)

[[ 1  2  3]
 [ 4  5  6]
 [ 1  2  3]
 [ 7  8  9]
 [ 4  5  6]
 [10 11 12]]


In [28]:
rows , counts = np.unique(arr, axis=0, return_counts=True)
duplicate = rows[counts>1]
duplicate

array([[1, 2, 3],
       [4, 5, 6]])

# 13. Calculate correlation between two arrays.

In [26]:
arr = np.array([1,2,3,4,5])

arr1 = np.array([6,7,8,9,10])

np.corrcoef(arr,arr1)

array([[1., 1.],
       [1., 1.]])