In [1]:
import numpy as np 

# 14. Calculate the Euclidean distance between two points.

In [7]:
x  = np.array([1,2,3,4,5])

y = np.array([6,7,8,9,10])

d = np.sqrt(np.sum((x - y )**2))

print(d)

11.180339887498949


# 15. Perform matrix multiplication using NumPy.

In [29]:
arr1 = np.array([[1,2,3],
              [4,5,6],
              [7,8,9],
            
             ])

arr2 = np.array([[10,11,12],
                [13,14,15],
               [16,17,18]])
print("1st Matrics",arr1)

print("2nd Matrics",arr2)

result = np.matmul(arr1,arr2)

print("Final Results",
      result)

1st Matrics [[1 2 3]
 [4 5 6]
 [7 8 9]]
2nd Matrics [[10 11 12]
 [13 14 15]
 [16 17 18]]
Final Results [[ 84  90  96]
 [201 216 231]
 [318 342 366]]
