# 10. Replace NaN values with the column mean.

In [1]:
import numpy as np

In [33]:
arr = np.array([10,20,np.nan,40,np.nan,60,70,80,np.nan,100])
mean = np.nanmean(arr)
arr[np.isnan(arr)] = mean
arr

array([ 10.        ,  20.        ,  54.28571429,  40.        ,
        54.28571429,  60.        ,  70.        ,  80.        ,
        54.28571429, 100.        ])

# 11. Generate a 10×10 matrix of random numbers.

In [44]:
g = np.random.randint(10,200,100)
g 

array([ 72, 185,  82, 104,  79,  28,  77,  28, 161, 102, 124, 165, 120,
       177,  34, 191, 184, 100, 191,  57, 111, 137,  23, 141, 133, 130,
        45, 151,  39,  35, 137,  22,  28,  28, 105,  84, 105,  19,  63,
        61, 148, 157, 135,  60,  30,  81,  84, 148,  16,  48, 190,  14,
       110, 101,  33,  46, 176, 181, 174,  73,  85, 184, 160,  51,  17,
       118,  47,  88, 188, 198, 199, 126,  52,  60,  31,  36,  56,  33,
       124, 140, 136, 199,  90, 168, 139,  54, 142, 146, 163,  68, 191,
        49,  69, 124, 176, 145,  13, 151, 108, 177], dtype=int32)

In [45]:
g.reshape(10,10)

array([[ 72, 185,  82, 104,  79,  28,  77,  28, 161, 102],
       [124, 165, 120, 177,  34, 191, 184, 100, 191,  57],
       [111, 137,  23, 141, 133, 130,  45, 151,  39,  35],
       [137,  22,  28,  28, 105,  84, 105,  19,  63,  61],
       [148, 157, 135,  60,  30,  81,  84, 148,  16,  48],
       [190,  14, 110, 101,  33,  46, 176, 181, 174,  73],
       [ 85, 184, 160,  51,  17, 118,  47,  88, 188, 198],
       [199, 126,  52,  60,  31,  36,  56,  33, 124, 140],
       [136, 199,  90, 168, 139,  54, 142, 146, 163,  68],
       [191,  49,  69, 124, 176, 145,  13, 151, 108, 177]], dtype=int32)